### ISSUE TITLE
MAPL 2.40.3.1 failed on WCOSS2

### ISSUE THREAD

**Issue by WeiWei-NCO** [NOAA-EMC/WCOSS2-requests#34]
In a recent test, install of MAPL failed with the following error msg. 

```
  Could NOT find ESMF: Found unsuitable version "8.5.0", but required is at
  least "8.6.1" (found
```

It builds 2.40.3.1 even with `mapl@2.40.3` in spack.yaml. Looks like 4 digits version doesn't go well with 3 digits. 
```
==> Concretized mapl@2.40.3
 -   qjskkfj  mapl@2.40.3.1%intel@19.1.3.304 cflags="-static-libgcc -static-libstdc++ -Bstatic -lstdc++ -Bdynamic -lm -lpthread" cxxflags="-static-libgcc -static-libstdc++ -Bstatic -lstdc++ -Bdynamic -lm -lpthread" fflags="-static-libgcc -static-libstdc++ -Bstatic -lstdc++ -Bdynamic -lm -lpthread" ~debug~extdata2g~f2py~fargparse~ipo~pflogger~pfunit~shared build_system=cmake build_type=Release generator=make arch=linux-sles15-zen2
```

Had to take 2.40.3.1 out of mapl package.py.

**Comment by AlexanderRichert-NOAA** [comment]
Yeah I see the issue, I'll update common/packages.yaml (spack automatically tries to use sub-versions unless you use the syntax `mapl@=2.40.3`).

**Comment by AlexanderRichert-NOAA** [comment]
I updated https://github.com/JCSDA/spack-stack/blob/release/1.6.0-nco/configs/common/packages.yaml, and another quick workaround would be to explicitly put `mapl@=2.40.3` in your specs.

**Comment by WeiWei-NCO** [comment]
The updated packages.yaml doesn't seem to work. It concertizes as 2.43.2.

Adding `mapl@=2.40.3` to spack.yaml worked.

**Comment by AlexanderRichert-NOAA** [comment]
What are the settings for MAPL in common/packages.yaml and site/packages.yaml? I thought for 1.6.0 the common setting was '@=2.40.3'.

**Comment by WeiWei-NCO** [comment]
not in site/packages.yaml

commom/packages.yaml
```
    mapl:
      # 2.35.2 goes with esmf@8.4.2, 2.40.3 goes with esmf@8.5.0
      # turn off ~pflogger and extdata2g to avoid compilation
      # errors with intel@2021.7.0+, see
      # https://github.com/JCSDA/spack-stack/issues/769
      # also: ... extdata2g segfault UFS?
      require: '@=2.40.3'
#      version: ['2.40.3']
      variants: ~shared ~extdata2g ~pflogger
      #version: ['2.46.2']
      #variants: +pflogger
```
